export const categories = [
    { name: 'Lastik', url: '#' },
    { name: 'Otomobil Lastikleri', url: '#' },
    { name: 'SUV 4x4 Lastikleri', url: '#' },
    { name: 'Hafif Ticari Lastikleri', url: '#' },
    { name: 'Midibüs/Kamyonet Lastikleri', url: '#' },
    { name: 'Ağır Vasıta Lastikleri', url: '#' },
    { name: 'Ağır Vasıta Uzun Yol Lastikleri', url: '#' },
    { name: 'Ağır Vasıta Bölgesel Lastikler', url: '#' },
    { name: 'Ağır Vasıta Şehir İçi Lastikler', url: '#' },
    { name: 'Ağır Vasıta Şantiye Lastikleri', url: '#' },
    { name: 'Ağır Vasıta Yol Dışı Lastikleri', url: '#' },
    { name: 'Zirai Lastikleri', url: '#' },
    { name: 'Traktör Radyal Lastikler', url: '#' },
    { name: 'Forklift Lastikleri', url: '#' },
    { name: 'Forklift Havalı Lastikler', url: '#' },
    { name: 'Forklift Dolgu Lastikler', url: '#' },
    { name: 'Akü', url: '#' },
    { name: 'Otomobil ve Hafif Ticari Aküleri', url: '#' },
    { name: 'Ağır Hizmet Ticari Araç Aküleri', url: '#' },
    { name: 'Marin Aküler', url: '#' },
    { name: 'Enerji ve Solar Aküler', url: '#' },
    { name: 'Jant', url: '#' },
    { name: 'Yağ', url: '#' }
  ];
  
  export const tireSizes = [
    { size: '175/65R14', url: '#' },
    { size: '185/65R14', url: '#' },
    { size: '195/60R15', url: '#' },
    { size: '195/65R15', url: '#' },
    { size: '205/55R16', url: '#' },
    { size: '215/55R16', url: '#' },
    { size: '195/60R16', url: '#' },
    { size: '205/60R16', url: '#' },
    { size: '215/50R17', url: '#' },
    { size: '215/55R17', url: '#' },
    { size: '205/40R17', url: '#' },
    { size: '215/45R17', url: '#' },
    { size: '225/45R17', url: '#' },
    { size: '225/50R17', url: '#' },
    { size: '245/40R17', url: '#' },
    { size: '225/40R18', url: '#' },
    { size: '225/45R18', url: '#' },
    { size: '215/55R18', url: '#' },
    { size: '205/55R19', url: '#' },
    { size: '255/40R19', url: '#' },
    { size: '305/30R19', url: '#' },
    { size: '275/40R20', url: '#' },
    { size: '295/35R21', url: '#' }
  ];
  
  export const brands = [
    { brand: 'Michelin', url: '#' },
    { brand: 'Bridgestone', url: '#' },
    { brand: 'Goodyear', url: '#' },
    { brand: 'Continental', url: '#' },
    { brand: 'Hankook', url: '#' },
    { brand: 'Pirelli', url: '#' },
    { brand: 'Yokohama', url: '#' },
    { brand: 'Dunlop', url: '#' },
    { brand: 'Lassa', url: '#' },
    { brand: 'Petlas', url: '#' },
    { brand: 'BF Goodrich', url: '#' },
    { brand: 'Dayton', url: '#' },
    { brand: 'Falken', url: '#' },
    { brand: 'Formula', url: '#' },
    { brand: 'Kormoran', url: '#' },
    { brand: 'Kumho', url: '#' },
    { brand: 'Nexen', url: '#' },
    { brand: 'Nokian', url: '#' },
    { brand: 'Özka', url: '#' },
    { brand: 'Sava', url: '#' },
    { brand: 'Energy', url: '#' },
    { brand: 'İnci', url: '#' },
    { brand: 'Mutlu', url: '#' }
  ];