export const products = [
    {
      id: 1,
      imageUrl: "/images/lastik.jpg", 
      title: "Lassa",
      description: "235/65R16C 12PR 121/119N Lassa Wintus 2 M+S", 
      price: "1796,00 ", 
      hasSpecialIcon: true,
      discount: 20,
      tamir: true,
    },
    {
      id: 2,
      imageUrl: "/images/lastik.jpg",
      title: "Bridgestone",
      description: "235/65R17 108V Bridgestone Dueler H/P Sport",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: 60,
      tamir: true,
    },
    {
      id: 3,
      imageUrl: "/images/lastik.jpg",
      title: "Michelin",
      description: "235/65R17 108V Michelin Latitude Tour HP",
      price: "1900,00 ",
      hasSpecialIcon: false,
      discount: 50,
      tamir: true,
    },
    {
      id: 4,
      imageUrl: "/images/lastik.jpg",
      title: "Pirelli",
      description: "235/65R17 108V Pirelli Scorpion Verde",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: false,
    },
    {
      id: 5,
      imageUrl: "/images/lastik.jpg",
      title: "Goodyear",
      description: "235/65R17 108V Goodyear EfficientGrip SUV",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 6,
      imageUrl: "/images/lastik.jpg",
      title: "Continental",
      description: "235/65R17 108V Continental ContiCrossContact LX 2",
      price: "1899,00 ",
      hasSpecialIcon: true,
      discount: false,
      tamir: true,
    },
    {
      id: 7,
      imageUrl: "/images/lastik.jpg",
      title: "Hankook",
      description: "235/65R17 108V Hankook Dynapro HP2 RA33",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: false,
    },
    {
      id: 8,
      imageUrl: "/images/lastik.jpg",
      title: "Dunlop",
      description: "235/65R17 108V Dunlop SP QuattroMaxx",
      price: "1899,00 ",
      hasSpecialIcon: true,
      discount: false,
      tamir: false,
    },
    {
      id: 9,
      imageUrl: "/images/lastik.jpg",
      title: "Lassa",
      description: "235/65R16C 12PR 121/119N Lassa Wintus 2 M+S",
      price: "1796,00 ",
      hasSpecialIcon: false,
      discount: 70,
      tamir: false,
    },
    {
      id: 10,
      imageUrl: "/images/lastik.jpg",
      title: "Bridgestone",
      description: "235/65R17 108V Bridgestone Dueler H/P Sport",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 11,
      imageUrl: "/images/lastik.jpg",
      title: "Michelin",
      description: "235/65R17 108V Michelin Latitude Tour HP",
      price: "1900,00 ",
      hasSpecialIcon: false,
      discount: 50,
      tamir: false,
    },
    {
      id: 12,
      imageUrl: "/images/lastik.jpg",
      title: "Pirelli",
      description: "235/65R17 108V Pirelli Scorpion Verde",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 13,
      imageUrl: "/images/lastik.jpg",
      title: "Goodyear",
      description: "235/65R17 108V Goodyear EfficientGrip SUV",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 14,
      imageUrl: "/images/lastik.jpg",
      title: "Continental",
      description: "235/65R17 108V Continental ContiCrossContact LX 2",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: 20,
      tamir: false,
    },
    {
      id: 15,
      imageUrl: "/images/lastik.jpg",
      title: "Hankook",
      description: "235/65R17 108V Hankook Dynapro HP2 RA33",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 16,
      imageUrl: "/images/lastik.jpg",
      title: "Dunlop",
      description: "235/65R17 108V Dunlop SP QuattroMaxx",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 17,
      imageUrl: "/images/lastik.jpg",
      title: "Lassa",
      description: "235/65R16C 12PR 121/119N Lassa Wintus 2 M+S",
      price: "1796,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 18,
      imageUrl: "/images/lastik.jpg",
      title: "Bridgestone",
      description: "235/65R17 108V Bridgestone Dueler H/P Sport",
      price: "1899,00 ",
      hasSpecialIcon: true,
      discount: 20,
      tamir: false,
    },
    {
      id: 19,
      imageUrl: "/images/lastik.jpg",
      title: "Michelin",
      description: "235/65R17 108V Michelin Latitude Tour HP",
      price: "1900,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 20,
      imageUrl: "/images/lastik.jpg",
      title: "Pirelli",
      description: "235/65R17 108V Pirelli Scorpion Verde",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: 50,
      tamir: false,
    },
    {
      id: 21,
      imageUrl: "/images/lastik.jpg",
      title: "Goodyear",
      description: "235/65R17 108V Goodyear EfficientGrip SUV",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 22,
      imageUrl: "/images/lastik.jpg",
      title: "Continental",
      description: "235/65R17 108V Continental ContiCrossContact LX 2",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 23,
      imageUrl: "/images/lastik.jpg",
      title: "Hankook",
      description: "235/65R17 108V Hankook Dynapro",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 24,
      imageUrl: "/images/lastik.jpg",
      title: "Dunlop",
      description: "235/65R17 108V Dunlop SP QuattroMaxx",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: false,
    },
    {
      id: 25,
      imageUrl: "/images/lastik.jpg",
      title: "Lassa",
      description: "235/65R16C 12PR 121/119N Lassa Wintus 2 M+S",
      price: "1796,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: false,
    },
    {
      id: 26,
      imageUrl: "/images/lastik.jpg",
      title: "Bridgestone",
      description: "235/65R17 108V Bridgestone Dueler H/P Sport",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 27,
      imageUrl: "/images/lastik.jpg",
      title: "Michelin",
      description: "235/65R17 108V Michelin Latitude Tour HP",
      price: "1900,00 ",
      hasSpecialIcon: false,
      discount: 50,
      tamir: false,
    },
    {
      id: 28,
      imageUrl: "/images/lastik.jpg",
      title: "Pirelli",
      description: "235/65R17 108V Pirelli Scorpion Verde",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 29,
      imageUrl: "/images/lastik.jpg",
      title: "Goodyear",
      description: "235/65R17 108V Goodyear EfficientGrip SUV",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    {
      id: 30,
      imageUrl: "/images/lastik.jpg",
      title: "Continental",
      description: "235/65R17 108V Continental ContiCrossContact LX 2",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: 20,
      tamir: false,
    },
    {
      id: 31,
      imageUrl: "/images/lastik.jpg",
      title: "Hankook",
      description: "235/65R17 108V Hankook Dynapro HP2",
      price: "1899,00 ",
      hasSpecialIcon: false,
      discount: false,
      tamir: true,
    },
    
  ];